// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
  user_id,
  name,
  phone_number,
  image_uri,
  type,
  is_pinned
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, name, phone_number, image_uri, type, is_pinned, created_at, updated_at
`

type CreateContactParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	PhoneNumber string      `json:"phone_number"`
	ImageUri    *string     `json:"image_uri"`
	Type        *string     `json:"type"`
	IsPinned    *bool       `json:"is_pinned"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.UserID,
		arg.Name,
		arg.PhoneNumber,
		arg.ImageUri,
		arg.Type,
		arg.IsPinned,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.ImageUri,
		&i.Type,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = $1 AND user_id = $2
`

type DeleteContactParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.UserID)
	return err
}

const getContactById = `-- name: GetContactById :one
SELECT id, user_id, name, phone_number, image_uri, type, is_pinned, created_at, updated_at FROM contacts
WHERE id = $1 AND user_id = $2
`

type GetContactByIdParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetContactById(ctx context.Context, arg GetContactByIdParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactById, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.ImageUri,
		&i.Type,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContacts = `-- name: GetContacts :many
SELECT id, user_id, name, phone_number, image_uri, type, is_pinned, created_at, updated_at FROM contacts
WHERE user_id = $1
ORDER BY is_pinned DESC, name ASC
`

func (q *Queries) GetContacts(ctx context.Context, userID pgtype.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, getContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PhoneNumber,
			&i.ImageUri,
			&i.Type,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleContactPin = `-- name: ToggleContactPin :one
UPDATE contacts
SET
    is_pinned = NOT is_pinned,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, phone_number, image_uri, type, is_pinned, created_at, updated_at
`

type ToggleContactPinParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ToggleContactPin(ctx context.Context, arg ToggleContactPinParams) (Contact, error) {
	row := q.db.QueryRow(ctx, toggleContactPin, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.ImageUri,
		&i.Type,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const toggleContactType = `-- name: ToggleContactType :one
UPDATE contacts
SET
    type = CASE WHEN type = 'Trusted' THEN 'Casual' ELSE 'Trusted' END,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, phone_number, image_uri, type, is_pinned, created_at, updated_at
`

type ToggleContactTypeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ToggleContactType(ctx context.Context, arg ToggleContactTypeParams) (Contact, error) {
	row := q.db.QueryRow(ctx, toggleContactType, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.ImageUri,
		&i.Type,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET
  name = COALESCE($1, name),
  phone_number = COALESCE($2, phone_number),
  image_uri = COALESCE($3, image_uri),
  type = COALESCE($4, type),
  is_pinned = COALESCE($5, is_pinned),
  updated_at = now()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, name, phone_number, image_uri, type, is_pinned, created_at, updated_at
`

type UpdateContactParams struct {
	Name        *string     `json:"name"`
	PhoneNumber *string     `json:"phone_number"`
	ImageUri    *string     `json:"image_uri"`
	Type        *string     `json:"type"`
	IsPinned    *bool       `json:"is_pinned"`
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Name,
		arg.PhoneNumber,
		arg.ImageUri,
		arg.Type,
		arg.IsPinned,
		arg.ID,
		arg.UserID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.ImageUri,
		&i.Type,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
