// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    pgtype.Text        `json:"name"`
	PhoneNumber             pgtype.Text        `json:"phone_number"`
	ProfileImageUrl         pgtype.Text        `json:"profile_image_url"`
	BloodGroup              string             `json:"blood_group"`
	Allergies               pgtype.Text        `json:"allergies"`
	Medications             pgtype.Text        `json:"medications"`
	NotificationPreferences []byte             `json:"notification_preferences"`
	DeviceTokens            []byte             `json:"device_tokens"`
	IsActive                pgtype.Bool        `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt             pgtype.Timestamptz `json:"last_login_at"`
}
