// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    *string            `json:"name"`
	PhoneNumber             *string            `json:"phone_number"`
	ProfileImageUrl         *string            `json:"profile_image_url"`
	BloodGroup              *string            `json:"blood_group"`
	Allergies               *string            `json:"allergies"`
	Medications             *string            `json:"medications"`
	NotificationPreferences []byte             `json:"notification_preferences"`
	DeviceTokens            []byte             `json:"device_tokens"`
	IsActive                *bool              `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt             pgtype.Timestamptz `json:"last_login_at"`
}
