// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) CreateProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, phone_number, profile_image_url, blood_group, allergies, medications, notification_preferences, device_tokens, is_active, created_at, updated_at, last_login_at FROM profiles
WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.BloodGroup,
		&i.Allergies,
		&i.Medications,
		&i.NotificationPreferences,
		&i.DeviceTokens,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE profiles
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}
